# Generated by Django 6.0.3 on 2026-07-03 11:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('form_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizacion')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=30)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrs_membresias/')),
            ],
            options={
                'verbose_name': 'Membresia',
                'verbose_name_plural': 'Membresias',
                'db_table': 'membresia',
            },
        ),
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_actividad_fisica', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=20)),
                ('objetivo_nutricional', models.CharField(choices=[('perder_peso', 'Perder Peso'), ('mantener', 'Mantener'), ('ganar_masa', 'Ganar Masa Muscular')], max_length=20)),
                ('tipo_plan_alimenticio', models.CharField(choices=[('keto', 'Keto'), ('balanceada', 'Balanceada'), ('hiperproteica', 'Hiperproteica')], max_length=40)),
            ],
            options={
                'verbose_name': 'Nutricion',
                'verbose_name_plural': 'Nutriciones',
                'db_table': 'Nutricion',
            },
        ),
        migrations.CreateModel(
            name='Registrovisitantestemporales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Registro Visitante',
                'verbose_name_plural': 'Registros Visitantes',
                'db_table': 'registro_visitantes',
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=45, unique=True)),
                ('marca', models.CharField(max_length=45)),
                ('nombre_elemento', models.CharField(max_length=45)),
                ('unidad_peso', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2)),
                ('peso_elemento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('cantidad', models.IntegerField(default=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='elementos/')),
                ('nombre_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado')], max_length=20)),
                ('descripcion', models.TextField()),
                ('nombre_elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.elemento')),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion_interna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_certificacion', models.CharField(max_length=500)),
                ('fecha_certificacion', models.DateField()),
                ('descargado', models.BooleanField(default=False)),
                ('fk_membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.membresia', verbose_name='Membresía')),
            ],
            options={
                'verbose_name': 'Certificacion_interna',
                'verbose_name_plural': 'Certificaciones_internas',
                'db_table': 'Certificacion_interna',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateField(default=datetime.date.today, verbose_name='Fecha de Asistencia')),
                ('hora_ingreso', models.TimeField(blank=True, null=True, verbose_name='Hora de Ingreso')),
                ('fk_membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.membresia')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='Masa_corporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_control', models.DateField()),
                ('altura_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('estado_imc', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_Nutricion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutricion', to='gimnasio.nutricion', verbose_name='Nutricion')),
            ],
            options={
                'verbose_name': 'Masa_corporal',
                'verbose_name_plural': 'Masas_corporales',
                'db_table': 'Masa_corporal',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('short_answer', 'Respuesta corta'), ('paragraph', 'Párrafo'), ('multiple_choice', 'Opción múltiple'), ('check_boxes', 'Casillas de verificación'), ('dropdown', 'Lista desplegable'), ('linear_scale', 'Escala lineal'), ('date', 'Fecha'), ('time', 'Hora')], max_length=20)),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('requerida', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='gimnasio.encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'pregunta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rutina', models.CharField(choices=[('FUERZA', 'Fuerza'), ('CARDIO', 'Cardio'), ('FUNCIONAL', 'Funcional')], max_length=50)),
                ('dias_disponibles', models.IntegerField()),
                ('distribucion_rutina', models.CharField(choices=[('SUPERIOR', 'Superior'), ('INFERIOR', 'Inferior'), ('COMPLETA', 'Cuerpo completo')], max_length=30)),
                ('fk_imc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.masa_corporal')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'db_table': 'rutina',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=45, unique=True)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('apellido_usuario', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_usuario', models.CharField(max_length=45)),
                ('correo_usuario', models.CharField(max_length=100, unique=True)),
                ('peso_usuario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('altura_usuario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genero_usuario', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('rol', models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador')], max_length=30, null=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte')], default='CC', max_length=2)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('visitante', 'Visitante')], max_length=30)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Turnosentrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_turno_final', models.DateField(default=datetime.date.today)),
                ('jornada', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=10)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_entrenador', to='gimnasio.usuario')),
            ],
            options={
                'verbose_name': 'Turno Entrenador',
                'verbose_name_plural': 'Turnos Entrenadores',
                'db_table': 'turno_entrenadores',
            },
        ),
        migrations.CreateModel(
            name='Soporte_PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peticion', 'Peticion'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], default='peticion', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('en_proceso', 'en_proceso'), ('solucionada', 'solucionada')], default='pendiente', max_length=20)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.usuario')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
                'db_table': 'PQRS',
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_sancion', models.CharField(max_length=350)),
                ('tipo_sancion', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('duracion_sancion', models.IntegerField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('pendiente', 'Pendiente')], max_length=80)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sancion',
                'verbose_name_plural': 'Sanciones',
                'db_table': 'Sancion',
            },
        ),
        migrations.CreateModel(
            name='Reportes_estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('membresia', 'Membresia'), ('asistencia', 'Asistencia'), ('elemento', 'Elemento')], default='membresia', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_generacion', models.DateField(default=datetime.date.today)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'Reporte',
            },
        ),
        migrations.AddField(
            model_name='nutricion',
            name='fk_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.usuario'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('MEMBRESIA', 'Membresía'), ('MANTENIMIENTO', 'Mantenimiento'), ('ASISTENCIA', 'Asistencia')], max_length=120, verbose_name='Tipo de Notificacion')),
                ('canal_notificacion', models.CharField(choices=[('SMS', 'SMS'), ('CORREO', 'Correo')], max_length=120, verbose_name='Canal de Notificacion')),
                ('estado_notificacion', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('NO ASIGNADA', 'No asignada')], max_length=120, verbose_name='Estado de Notificacion')),
                ('detalle_notificacion', models.CharField(choices=[('Bienvenida', 'BIENVENIDA'), ('Membresía_activada', 'MEMBRESIA_ACTIVADA'), ('Próxima_a_vencer', 'VENCIMIENTO'), ('Membresía_vencida', 'VENCIDA'), ('Inasistencia', 'INASISTENCIA'), ('Mantenimiento_programado', 'MANTENIMIENTO_PROGRAMADO')], max_length=120)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.usuario')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='membresia',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.usuario'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.usuario'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='encuestas', to='gimnasio.usuario'),
        ),
    ]
