# Generated by Django 6.0.3 on 2026-07-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportes_estadisticas',
            options={'ordering': ['-fecha_generacion'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AddField(
            model_name='reportes_estadisticas',
            name='tipo_archivo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportes_estadisticas',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reportes_estadisticas',
            name='tipo_reporte',
            field=models.CharField(choices=[('usuarios', 'Usuarios'), ('membresia', 'Membresías'), ('asistencia', 'Asistencias'), ('elemento', 'Elementos'), ('mantenimiento', 'Mantenimientos'), ('pqrs', 'PQRS'), ('sancion', 'Sanciones'), ('visitantes', 'Visitantes Temporales'), ('turnos', 'Turnos de Entrenadores'), ('certificaciones', 'Certificaciones Internas'), ('estadisticas', 'Reportes y Estadísticas')], max_length=30),
        ),
    ]
