"""
Django settings for gimnasio_naza project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import logging
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY
# En Render, SECRET_KEY y DEBUG se definen como variables de entorno.
# El valor de aquí abajo solo se usa como respaldo para correr en local.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-#^wh7s#z^gtl*-emy_098o6um-5gt^y^-9hcue^_4&bxi8=i$n',
)
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',
]

# Render recibe las peticiones por HTTPS pero se las reenvía a este contenedor
# por HTTP normal. Sin esto, Django cree que todo llega por HTTP y rechaza los
# POST (por ejemplo el login) con error de CSRF.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']


# APPLICATIONS
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'login',
    'gimnasio',
    'qr_code',
    'usuarios',
]


# MIDDLEWARE
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# URLS
ROOT_URLCONF = 'config.urls'


# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# DATABASE
# SQLite: el archivo se guarda en /data para que el volumen de Docker lo persista.
# Se crea la carpeta automáticamente si no existe (evita "unable to open database file"
# tanto en CI como al levantar el contenedor por primera vez).
DB_DIR = BASE_DIR / 'data'
DB_DIR.mkdir(parents=True, exist_ok=True)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_DIR / 'db.sqlite3',
    }
}


# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# INTERNATIONALIZATION
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_TZ = True
USE_I18N = True


# STATIC FILES (CSS, JS, IMAGES)
STATIC_URL = '/static/'

# Django busca automáticamente en las carpetas static/ de cada app instalada.
# No usamos STATICFILES_DIRS porque no existe una carpeta "static/" en la raíz
# del proyecto, y Django lanza error en collectstatic si apunta a una carpeta
# que no existe.

# Carpeta usada cuando se ejecuta collectstatic (producción)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration
WHITENOISE_USE_FINDERS = True
WHITENOISE_STATIC_ROOT = STATIC_ROOT


# DEFAULT PRIMARY KEY
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# LOGIN / LOGOUT
LOGIN_REDIRECT_URL = 'gimnasio:dashboard'
LOGOUT_REDIRECT_URL = 'login:login'
LOGIN_URL = 'login:login'
LOGOUT_URL = 'login:logout'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Requerido desde Django 4.2+ para manejar los ImageField/FileField (fotos, QR, etc.)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# EMAIL CONFIGURATION
# La contraseña NUNCA se escribe aquí: se lee desde una variable de entorno
# que defines en Render (Dashboard -> Environment). La contraseña anterior
# quedó expuesta en el repositorio público y debe considerarse inválida.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'gymnazareth@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.core.mail': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Cierre automático de sesión (1 hora = 3600 segundos)
SESSION_COOKIE_AGE = 3600
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True  # Reinicia el contador si el usuario hace clic en algo
